server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6380
    database: 0
    password: redistest
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:commerceDB
  jpa:
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console